name: Add issues to Painel de Issues

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://venha-pra-nuvem.ghe.com/orgs/venha-pra-nuvem/projects/35
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}